### PR TITLE
Major update of ibaqpy

### PR DESCRIPTION
**Pull request by WangHong007**

### CODE REVIEW

**Comment by WangHong007** [comment]
@ypriverol I think we've got back to the commit we want, but let @zprobot test and update it first and then merge the PR. What do you think?

**Comment by WangHong007** [comment]
@ypriverol After testing by @zprobot, this PR could be merged. Please check all changes again.

**Comment by ypriverol** [comment]
@WangHong007 @zprobot We have two PR now, #45 #46 Please coordinate which one is the last one with the refactoring.

**Comment by ypriverol** [comment]
Agreed. Remember always to update the README.

**Comment by WangHong007** [comment]
@ypriverol PR is ready, please take a look. #46 should be closed.

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
